# Generated by Django 5.1.1 on 2024-09-22 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_order_date_alter_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 9, 22, 11, 21, 45, 725455)),
        ),
    ]
